[project]
name = "pycad"
description = "2D CAD for Electronics Design /Python/"
authors = [
    { name = "Dmitry Ponyatov", email = "<dponyatov@gmail.com>" },
    { name = "DeepSeek Chat" },
]
dynamic = ["version"]
requires-python = ">= 3.11"
dependencies = ["PyQt6 >= 6.4.2", "ply >= 3.11"]

[build-system]
requires = ["setuptools", "wheel", "setuptools-git-versioning"]
build-backend = "setuptools.build_meta"

[tool.setuptools-git-versioning]
enabled = true
